modLoader="javafml"
loaderVersion="[28,)"
[[mods]] 
modId="horsestats" 
version="1.0.1" 
displayName="Horse Stats" 
authors="lerrific" 
description='''
A simple mod that allows you to shift right click (with a stick) on a horse to see it's stats.
'''